ptools:
  analyze_and_synthesize_evidence:
    backoff: true
    learner: codedistill
    method: learned_code
  answer_question:
    learner: ptool_inducer
    method: simulate_pydantic
    tool_module: __learned__
    tools:
    - gather_evidence
    - search_suspect_attributes
    - analyze_and_synthesize_evidence
    - form_conclusion
    - plan_investigation_approach
  form_conclusion:
    backoff: true
    learner: codedistill
    method: learned_code
  search_suspect_attributes:
    backoff: true
    learner: codedistill
    method: learned_code
