llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
cachier:
  cache_dir: benchmarks/bbh/geometric_shapes/llm_cache
evaluate:
  result_dir: benchmarks/bbh/geometric_shapes/val_results
  expt_name: geometric_shapes_val_class1v2
dataset:
  split: valid
  shuffle_seed: 137
  'n': 30
ptools:
  extract_path_and_options:
    method: learned_code
    backoff: true
    learner: codedistill
  decompose_path:
    method: learned_code
    backoff: true
    learner: codedistill
  describe_command:
    method: learned_code
    backoff: true
    learner: codedistill
  compute_angle:
    method: simulate
  describe_shape:
    method: simulate
  select_option:
    method: learned_code
    backoff: true
    learner: codedistill
  identify_shape:
    method: direct
    fn: ptools.geometric_shapes_workflow
learn:
  train_dir: benchmarks/bbh/geometric_shapes/learned_v2
