llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
cachier:
  cache_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/penguins_in_a_table/llm_cache
evaluate:
  result_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/penguins_in_a_table/val_results_full
  expt_name: penguins_in_a_table_val_full_class2v4
dataset:
  split: valid
  shuffle_seed: 137
  'n': 43
ptools:
  analyze_input:
    method: simulate
  table_operation:
    method: simulate
  answer_question:
    method: simulate
  choose_response:
    method: simulate
  answer_penguin_question:
    method: learned_code
    learner: workflow_distill
    backoff: true
learn:
  train_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/penguins_in_a_table/learned_class2_v4
root: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/penguins_in_a_table
