llm:
  model: together_ai/deepseek-ai/DeepSeek-V3
cachier:
  cache_dir: /Users/anon/reasoning_primitives/benchmarks/natural_plan/llm_cache
  enable_caching: false
evaluate:
  expt_name: trip_induced_llm_test_seed42
  result_dir: /Users/anon/reasoning_primitives/benchmarks/natural_plan/results
  entry_point: trip_planning
  record_details: true
dataset:
  split: trip
  prompt_mode: 0shot
  partition: test
  shuffle_seed: 42
ptools:
  trip_react_solve:
    method: react_pydantic
    tools:
    - ptools_common.finish
    - induced_ptools_seed42_correct_llm_trip.define_problem_and_strategy
    - induced_ptools_seed42_correct_llm_trip.search_constraint_details
    - induced_ptools_seed42_correct_llm_trip.search_flight_network
  trip_planning:
    method: direct
    fn: ptools_common.trip_react_impl
