ptools:
  answer_question:
    backoff: true
    learner: codedistill
    method: learned_code
  choose_response:
    backoff: true
    learner: codedistill
    method: learned_code
  table_operation:
    backoff: true
    learner: codedistill
    method: learned_code
