ptools:
  analyze_sentence:
    backoff: true
    learner: codedistill
    method: learned_code
  consistent_sports:
    backoff: true
    learner: codedistill
    method: learned_code
  sport_for:
    backoff: true
    learner: codedistill
    method: learned_code
