llm:
  model: together_ai/deepseek-ai/DeepSeek-V3
cachier:
  cache_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/musr/llm_cache
  enable_caching: false
evaluate:
  expt_name: musr_object_react_train_full
  result_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/musr/recordings_full
  entry_point: answer_question
  record_details: true
dataset:
  split: object_placements_train
  shuffle_seed: 42
  'n': 75
ptools:
  react_solve:
    method: simulate_pydantic
    tools:
    - ptools_common.search
    - ptools_common.lookup
    - ptools_common.finish
  answer_question:
    method: direct
    fn: ptools_common.react_answer_impl
root: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/musr
