llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
cachier:
  cache_dir: benchmarks/bbh/geometric_shapes/llm_cache
evaluate:
  result_dir: benchmarks/bbh/geometric_shapes/val_results_full
  expt_name: geometric_shapes_val_full_class2_opus
dataset:
  split: valid
  shuffle_seed: 137
  'n': 75
ptools:
  extract_path_and_options:
    method: simulate
  decompose_path:
    method: simulate
  describe_command:
    method: simulate
  compute_angle:
    method: simulate
  describe_shape:
    method: simulate
  select_option:
    method: simulate
  identify_shape:
    method: learned_code
    learner: workflow_distill
    backoff: true
learn:
  train_dir: benchmarks/bbh/geometric_shapes/learned_class2_opus
root: benchmarks/bbh/geometric_shapes
