llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
cachier:
  cache_dir: benchmarks/bbh/sports_understanding/llm_cache
evaluate:
  result_dir: benchmarks/bbh/sports_understanding/val_results
  expt_name: sports_understanding_val_baseline
dataset:
  split: valid
  shuffle_seed: 137
  'n': 30
ptools:
  analyze_sentence:
    method: simulate
  sport_for:
    method: simulate
  consistent_sports:
    method: simulate
  are_sports_in_sentence_consistent:
    method: direct
    fn: ptools.sports_understanding_workflow
