llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
  thinking: true
cachier:
  cache_dir: benchmarks/musr/llm_cache
  enable_caching: false
evaluate:
  expt_name: musr_object_induced_seed_ptools_deepseek_v3_1
  result_dir: benchmarks/musr/test_results_full
  entry_point: answer_question_workflow
  record_details: true
  max_workers: 1
dataset:
  split: object_placements_test
  shuffle_seed: 42
  'n': null
ptools:
  raw_answer:
    method: simulate
  extract_index:
    method: simulate
  infer_belief:
    method: simulate
  answer_question:
    method: direct
  answer_question_workflow:
    method: direct
    fn: __learned__.answer_question_workflow_orchestrated_seed
    learner: orch_learner
learn:
  train_dir: benchmarks/COMMON/orchestrator-results/_train_dirs/induced_seed_from_ptools/musr_object
root: benchmarks/musr
