ptools:
  extract_final_number:
    backoff: true
    learner: codedistill
    method: learned_code
dataset:
  split: valid
  'n': 100
learn:
  train_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/finqa/learned_v2
evaluate:
  expt_name: finqa_val_full_class1v2_REEVAL
  result_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/finqa/val_results_full
root: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/finqa
