llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
cachier:
  cache_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/date_understanding/llm_cache
evaluate:
  result_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/date_understanding/val_results
  expt_name: date_understanding_val_class2
dataset:
  split: valid
  shuffle_seed: 137
  'n': 30
ptools:
  find_date_from_sentence:
    method: simulate
  normalize_date_order:
    method: simulate
  find_time_difference:
    method: simulate
  identify_time_difference:
    method: simulate
  adjust_date_by_hours:
    method: simulate
  parse_question:
    method: simulate
  select_closest_option:
    method: simulate
  answer_date_question:
    method: learned_code
    learner: workflow_distill
    backoff: false
  answer_date_question_orchestrated:
    method: direct
    fn: ptools.zeroshot_unstructured_workflow
learn:
  train_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/date_understanding/learned_class2_v3
