llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
cachier:
  cache_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/geometric_shapes/llm_cache
evaluate:
  result_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/geometric_shapes/val_results
  expt_name: geometric_shapes_val_class2
dataset:
  split: valid
  shuffle_seed: 137
  'n': 30
ptools:
  extract_path_and_options:
    method: simulate
  decompose_path:
    method: simulate
  describe_command:
    method: simulate
  compute_angle:
    method: simulate
  describe_shape:
    method: simulate
  select_option:
    method: simulate
  identify_shape:
    method: learned_code
    learner: workflow_distill
    backoff: false
learn:
  train_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/geometric_shapes/learned_class2
