llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
cachier:
  cache_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/natural_plan/llm_cache
  enable_caching: false
evaluate:
  expt_name: calendar_zs_cot_train
  result_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/natural_plan/recordings_class3
  entry_point: calendar_scheduling
  prompt_trace: true
  record_details: true
dataset:
  split: calendar
  partition: train
  shuffle_seed: 42
  prompt_mode: 0shot
  'n': 50
ptools:
  parse_schedules:
    method: simulate
  find_available_slots:
    method: simulate
  select_and_format:
    method: simulate
  calendar_scheduling:
    method: prompt_llm
    prompt_template_file: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/natural_plan/prompt_templates/calendar_zs_cot.txt
