llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
  thinking: true
cachier:
  cache_dir: C:\Users\STUDENT\OneDrive\Documents\Projects\AI Research\secretagent\benchmarks\musr\llm_cache
evaluate:
  expt_name: nsga_028
  result_dir: C:\Users\STUDENT\OneDrive\Documents\Projects\AI Research\secretagent\benchmarks\musr\results
  entry_point: answer_question
dataset:
  split: team_allocation_val
  shuffle_seed: 42
  'n': 50
ptools:
  raw_answer:
    method: simulate
  extract_index:
    method: simulate
  answer_question:
    method: direct
    fn: ptools_common.react_answer_impl
  react_solve:
    method: simulate_pydantic
    tool_module: __learned__
    learner: ptool_inducer
    tools: __all__
  extract_team_requirements:
    method: simulate
    model: together_ai/openai/gpt-oss-20b
  score_team_assignments:
    method: simulate
    model: together_ai/openai/gpt-oss-120b
learn:
  train_dir: C:\Users\STUDENT\OneDrive\Documents\Projects\AI Research\secretagent\benchmarks\musr\learned\team
root: C:\Users\STUDENT\OneDrive\Documents\Projects\AI Research\secretagent\benchmarks\musr
