llm:
  model: together_ai/deepseek-ai/DeepSeek-V3.1
cachier:
  cache_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/sports_understanding/llm_cache
evaluate:
  result_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/sports_understanding/val_results_full
  expt_name: sports_understanding_val_full_class2v4
dataset:
  split: valid
  shuffle_seed: 137
  'n': 75
ptools:
  analyze_sentence:
    method: simulate
  sport_for:
    method: simulate
  consistent_sports:
    method: simulate
  are_sports_in_sentence_consistent:
    method: learned_code
    learner: workflow_distill
    backoff: true
learn:
  train_dir: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/sports_understanding/learned_class2_v4
root: /Users/yanjiarui/Desktop/Will_research/secretagent/benchmarks/bbh/sports_understanding
